import { describe, expect, it } from "vitest";
import { generateAiText, getAiProviderPublicStatus, resolveAiProviderSettings } from "./ai-provider";

const primaryKey = "sk-primary-12345678901234567890";
const fallbackKey = "ds-fallback-12345678901234567890";

describe("AI provider abstraction", () => {
  it("resolves OpenAI-compatible providers without exposing full API keys", () => {
    const status = getAiProviderPublicStatus({
      AI_PROVIDER: "deepseek",
      AI_API_KEY: "generic-key-12345678901234567890",
      AI_MODEL: "deepseek-reasoner",
      AI_FALLBACK_PROVIDER: "qwen",
      AI_FALLBACK_API_KEY: fallbackKey,
      AI_FALLBACK_BASE_URL: "https://dashscope.example/compatible-mode/v1",
      AI_FALLBACK_MODEL: "qwen-plus"
    });

    expect(status.activeProvider).toBe("deepseek");
    expect(status.primary.configured).toBe(true);
    expect(status.primary.baseUrl).toBe("https://api.deepseek.com");
    expect(status.primary.model).toBe("deepseek-reasoner");
    expect(status.primary.maskedApiKey).toBe("gene...7890");
    expect(status.primary.maskedApiKey).not.toContain("generic-key-12345678901234567890");
    expect(status.fallback).toMatchObject({ provider: "qwen", configured: true, model: "qwen-plus" });
  });

  it("falls back to the secondary provider when the primary request fails", async () => {
    const settings = resolveAiProviderSettings({
      AI_PROVIDER: "openai",
      OPENAI_API_KEY: primaryKey,
      AI_MODEL: "gpt-test",
      AI_FALLBACK_PROVIDER: "deepseek",
      AI_FALLBACK_API_KEY: fallbackKey,
      AI_FALLBACK_MODEL: "deepseek-test"
    });

    const result = await generateAiText(
      {
        messages: [
          { role: "system", content: "You are a test assistant." },
          { role: "user", content: "Generate." }
        ]
      },
      {
        settings,
        clientFactory: (config) => ({
          generateText: async () => {
            if (config.role === "primary") {
              throw new Error(`Request failed for ${primaryKey}`);
            }

            return { text: `generated by ${config.provider}` };
          }
        })
      }
    );

    expect(result).toMatchObject({ text: "generated by deepseek", provider: "deepseek", fallbackUsed: true });
    expect(result.attempts.map((attempt) => attempt.status)).toEqual(["failed", "success"]);
    expect(result.attempts[0].reason).not.toContain(primaryKey);
  });

  it("returns a user-friendly configuration error when no provider is configured", async () => {
    await expect(
      generateAiText(
        {
          messages: [{ role: "user", content: "Hello" }]
        },
        { env: { AI_PROVIDER: "qwen" } }
      )
    ).rejects.toThrow("AI provider belum dikonfigurasi");
  });
});
